task: rf_belebele_tur_Latn
dataset_path: facebook/belebele
test_split: test
dataset_name: tur_Latn
output_type: multiple_choice
num_fewshot: 0
doc_to_text: '{{flores_passage}}

  Question: {{question.strip()}}

  Answer:'
doc_to_choice: '{{[mc_answer1, mc_answer2, mc_answer3, mc_answer4]}}'
doc_to_target: '{{[''1'', ''2'', ''3'', ''4''].index(correct_answer_num)}}'
metric_list:
- metric: acc
  aggregation: mean
  higher_is_better: true
- metric: acc_norm
  aggregation: mean
  higher_is_better: true
metadata:
  version: 0.0
