task: bbh_cloze_formal_fallacies
dataset_path: SaylorTwift/bbh
dataset_name: formal_fallacies
test_split: test
output_type: multiple_choice
num_fewshot: 0
doc_to_text: '{{input}}

  Answer:'
doc_to_choice:
- invalid
- valid
doc_to_target: '{{["invalid", "valid"].index(target.strip())}}'
metric_list:
- metric: acc
  aggregation: mean
  higher_is_better: true
- metric: acc_norm
  aggregation: mean
  higher_is_better: true
metadata:
  version: 0.0
