"""Generated appendix tables: the 99 FineWeb-2 languages of the sweep, with the
setting at which each enters under schemes A and B and the number of benchmark
families the harness offers for it. Written to sections/app_tables_generated.tex.

    python make_appendix_tables.py
"""
import csv
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
sys.path.insert(0, str(REPO / "src"))
from evals.scripts.utils.configs import tasks_for_benchmarks  # noqa: E402

DATA = REPO / "src" / "pretrain" / "data"
OUT = HERE.parent / "sections" / "app_tables_generated.tex"


def esc(s):
    return str(s).replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def main():
    meta = {r["subset"]: r for r in csv.DictReader(open(DATA / "fineweb2-language-distribution.csv"))}
    sets = {s: json.load(open(DATA / f"language_sets_scheme{s}.json"))["sets"] for s in ("A", "B")}
    iso2 = json.load(open(REPO / "configs" / "languages.json"))["fineweb_iso2"]
    tasks = json.load(open(REPO / "configs" / "tasks.json"))
    auto = tasks["groups"]["auto"]

    def enters(scheme, subset):
        for L in (2, 8, 15, 30, 50, 100):
            if subset in sets[scheme].get(f"FW_L{L}", []):
                return L
        return None

    def n_families(subset):
        code = iso2.get(subset.split("_")[0])
        if not code:
            return 0
        names = tasks_for_benchmarks(auto, {code})
        return len({tasks["tasks"][t]["benchmark"] for t in names})

    rows = []
    for subset in sets["A"]["FW_L100"]:
        m = meta[subset]
        fam = m["family"].split(",")[0].split("(")[0].strip()
        rows.append((subset, m["name"], m["script"], fam, enters("A", subset), enters("B", subset), n_families(subset)))
    rows.append(("dclm", "English", "Latin", "Indo-European", 1, 1, n_families("eng_Latn") or 12))
    rows.sort(key=lambda r: (r[4] or 0, sets["A"]["FW_L100"].index(r[0]) if r[0] in sets["A"]["FW_L100"] else -1))

    def tab(part):
        lines = [r"\begin{tabular}{llllrrr}", r"\toprule",
                 r"Subset & Language & Script & Family & $L_A$ & $L_B$ & Fam. \\", r"\midrule"]
        for r in part:
            lines.append(" & ".join(esc(x) if x is not None else "--" for x in r) + r" \\")
        lines += [r"\bottomrule", r"\end{tabular}"]
        return "\n".join(lines)

    half = (len(rows) + 1) // 2
    body = "\n".join([
        "% Generated by documents/paper/figures/make_appendix_tables.py -- do not edit.",
        r"\begin{table}[p]", r"\centering", r"\tiny", r"\setlength{\tabcolsep}{2.5pt}",
        r"\caption{The languages of the sweep. $L_A$ and $L_B$ give the smallest language setting whose "
        r"scheme-A (resource-ranked) and scheme-B (diversity-first) list contains the subset; the lists are "
        r"nested, so a language is trained at every larger setting too. Fam.\ counts the benchmark families "
        r"of the pretraining suite that the harness offers for the language. English is the DCLM half of every "
        r"mixture. Family names are abbreviated to their top-level group.}",
        r"\label{tab:app-languages}",
        r"\begin{minipage}[t]{0.49\textwidth}\centering", tab(rows[:half]), r"\end{minipage}\hfill",
        r"\begin{minipage}[t]{0.49\textwidth}\centering", tab(rows[half:]), r"\end{minipage}",
        r"\end{table}", ""])
    OUT.write_text(body)
    print(f"wrote {OUT} ({len(rows)} languages)")
    cov = {}
    for r in rows:
        cov[r[6]] = cov.get(r[6], 0) + 1
    print("families per language:", dict(sorted(cov.items())))


if __name__ == "__main__":
    main()
