task: bbh_mcq_hyperbaton
dataset_path: SaylorTwift/bbh
dataset_name: hyperbaton
test_split: test
output_type: multiple_choice
num_fewshot: 0
doc_to_text: '{{input}}

  Answer:'
doc_to_choice: '{{labels}}'
doc_to_target: gold
metric_list:
- metric: acc
  aggregation: mean
  higher_is_better: true
- metric: acc_norm
  aggregation: mean
  higher_is_better: true
metadata:
  version: 0.0
process_docs: !function utils.process_docs
