#!/usr/bin/env python3
"""Generate the paper's data tables as LaTeX, regenerated from the configs/data
so they stay current. Three tables:

  1. languages   — the main language selection + metadata, from
                   ``configs/languages.json`` (groups.main; family/script/resource).
  2. benchmarks  — benchmark x language grid (check = covered), with capability
                   and training stage, all read from ``configs/tasks.json``
                   (benchmark_capabilities + per-task language/stages, language
                   coverage restricted to the main set).
  3. coverage    — per-model coverage of a model-set pool (default ``external``):
                   size, #checkpoints, #tasks, root benchmark families; built
                   from the eval parquet via ``analysis.utils.build_snr_pool``.

    python configs/generate_tables.py                  # all three -> configs/tables/
    python configs/generate_tables.py --only benchmarks
    python configs/generate_tables.py --pool custom_swissai_hf --outdir documents/tables
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
for _p in (_ROOT / "src" / "signal-and-noise", _ROOT / "src"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import pandas as pd  # noqa: E402

from analysis.utils import benchmark_family, build_snr_pool  # noqa: E402

LANGUAGES_JSON = _ROOT / "configs" / "languages.json"
TASKS_JSON = _ROOT / "configs" / "tasks.json"

# training-stage order + short labels used in the benchmark table
_STAGE_LABEL = {"pretraining": "pre", "midtraining": "mid", "posttraining": "post"}
_STAGE_ORDER = {"pre": 0, "mid": 1, "post": 2}
_CHECK = r"\checkmark"   # needs \usepackage{amssymb}


def _esc(s: str) -> str:
    out = str(s).replace("\\", r"\textbackslash{}")
    for ch in ("_", "&", "%", "#", "$"):
        out = out.replace(ch, "\\" + ch)
    return out


# --------------------------------------------------------------------------- #
# 1. languages
# --------------------------------------------------------------------------- #
def languages_table() -> str:
    cfg = json.loads(LANGUAGES_JSON.read_text())
    langs, main = cfg["languages"], cfg["groups"]["main"]
    rows, families, scripts, n_isolate = [], set(), set(), 0
    for code in main:
        m = langs[code]
        top = m["family"].split(",")[0].strip()
        if top.lower() == "isolate":
            n_isolate += 1
        else:
            families.add(top)
        scripts.add(m["script"])
        rows.append(f"{code} & {_esc(m['language'])} & {_esc(m['family'])} & "
                    f"{_esc(m['script'])} & {m['resource']} \\\\")
    isolate_str = (f"plus one isolate" if n_isolate == 1
                   else f"plus {n_isolate} isolates" if n_isolate else "")
    caption = (f"Language selection. We cover {len(families)} language families "
               f"{isolate_str}, {len(scripts)} writing systems, and high to "
               f"low-resource.").replace("  ", " ")
    return (
        "% Auto-generated by configs/generate_tables.py — do not edit by hand.\n"
        "\\begin{table*}[ht]\n\\centering\n\\small\n\\setlength{\\tabcolsep}{5pt}\n"
        f"\\caption{{{caption}}}\n\\label{{tab:languages}}\n"
        "\\begin{tabular}{lllll}\n\\toprule\n"
        "Code & Language & Family & Script & Resource \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n"
    )


# --------------------------------------------------------------------------- #
# 2. benchmarks x language grid
# --------------------------------------------------------------------------- #
def benchmarks_table() -> str:
    cfg = json.loads(TASKS_JSON.read_text())
    caps = cfg["benchmark_capabilities"]
    tasks = cfg["tasks"]
    main = json.loads(LANGUAGES_JSON.read_text())["groups"]["main"]
    main_set = set(main)

    blang: dict[str, set] = defaultdict(set)
    bstage: dict[str, set] = defaultdict(set)
    for meta in tasks.values():
        b = meta.get("benchmark")
        if b not in caps:
            continue
        lang = meta.get("language")
        if lang in main_set:
            blang[b].add(lang)
        for s in meta.get("stages", []):
            bstage[b].add(_STAGE_LABEL.get(s, s))

    def stage_key(b: str) -> int:
        return min((_STAGE_ORDER.get(s, 9) for s in bstage[b]), default=9)

    benches = sorted(caps, key=lambda b: (stage_key(b), b))

    col = "ll" + "c" * len(main)
    header = "Benchmark & Capability & " + " & ".join(main) + " \\\\"
    rows = []
    for b in benches:
        cells = [_CHECK if lg in blang[b] else "" for lg in main]
        rows.append(f"\\texttt{{{_esc(b)}}} & {_esc(caps[b])} & "
                    + " & ".join(cells) + " \\\\")
    return (
        "% Auto-generated by configs/generate_tables.py — do not edit by hand.\n"
        "% Requires \\usepackage{amssymb} for \\checkmark.\n"
        "\\begin{table*}[ht]\n\\centering\n\\small\n\\setlength{\\tabcolsep}{4pt}\n"
        "\\caption{Benchmark suite.}\n\\label{tab:benchmarks}\n"
        f"\\begin{{tabular}}{{{col}}}\n\\toprule\n{header}\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n"
    )


# --------------------------------------------------------------------------- #
# 3. per-model coverage of a pool
# --------------------------------------------------------------------------- #
def _root_family(task: str) -> str:
    """benchmark_family for the multilingual SNR families; first underscore
    token as the root for the broader reference suite it doesn't recognise."""
    fam = benchmark_family(task)
    return fam if fam != task else task.split("_")[0]


def coverage_table(pool: str) -> str:
    df = build_snr_pool(pool).copy()
    df["root"] = df["task"].map(_root_family)
    order = {s: i for i, s in enumerate(
        ["270M", "0.6B", "1B", "1.7B", "3B", "4B", "7B", "8B", "9B",
         "12B", "13B", "14B", "27B", "30B-A3B", "32B", "70B"])}
    rows = []
    for model, g in df.groupby("model"):
        rows.append({
            "model": model,
            "size": "/".join(sorted(set(g["size"].astype(str)))),
            "ckpts": int(g["step"].nunique()),
            "tasks": int(g["task"].nunique()),
            "families": int(g["root"].nunique()),
            "_k": order.get("/".join(sorted(set(g["size"].astype(str)))), 99),
        })
    t = pd.DataFrame(rows).sort_values(["_k", "model"])
    body = "\n".join(
        f"\\texttt{{{_esc(r.model)}}} & {_esc(r.size)} & {r.ckpts} & "
        f"{r.tasks} & {r.families} \\\\"
        for r in t.itertuples(index=False))
    return (
        "% Auto-generated by configs/generate_tables.py — do not edit by hand.\n"
        "\\begin{longtable}{@{}llrrr@{}}\n"
        f"\\caption{{Coverage of the \\texttt{{{_esc(pool)}}} model-set tier: "
        f"{len(t)} models. Tasks rolled up to their root benchmark family.}}"
        "\\\\\n\\toprule\nModel & Size & Ckpts & Tasks & Families \\\\\n"
        "\\midrule\n\\endfirsthead\n\\toprule\n"
        "Model & Size & Ckpts & Tasks & Families \\\\\n\\midrule\n\\endhead\n"
        "\\bottomrule\n\\endlastfoot\n" + body + "\n\\end{longtable}\n"
    )


def coverage_summary_table(pool: str) -> str:
    """Compact family x size-bucket grid: one row per model family, one column
    per size bucket, cell = number of checkpoints available there (``N (Km)``
    when K>1 models share the bucket). Blank where the family has no model."""
    from evals.scripts.utils.configs import bucket_order, size_bucket

    df = build_snr_pool(pool).copy()
    df["bucket"] = df["size"].map(size_bucket)
    per_model = (df.groupby(["family", "bucket", "model"])["step"].nunique()
                 .reset_index(name="ck"))
    agg = (per_model.groupby(["family", "bucket"])
           .agg(ck=("ck", "sum"), nm=("model", "nunique")).reset_index())
    cell = {(r.family, r.bucket): (int(r.ck), int(r.nm)) for r in agg.itertuples()}
    buckets = [b for b in bucket_order() if b in set(agg["bucket"])]
    families = sorted(agg["family"].unique())

    def fmt(f: str, b: str) -> str:
        if (f, b) not in cell:
            return ""
        ck, nm = cell[(f, b)]
        return str(ck) if nm == 1 else f"{ck} ({nm}m)"

    col = "l" + "r" * len(buckets)
    header = "Family & " + " & ".join(buckets) + " \\\\"
    rows = [f"\\texttt{{{_esc(f)}}} & " + " & ".join(fmt(f, b) for b in buckets) + " \\\\"
            for f in families]
    return (
        "% Auto-generated by configs/generate_tables.py — do not edit by hand.\n"
        "\\begin{table*}[ht]\n\\centering\n\\small\n\\setlength{\\tabcolsep}{5pt}\n"
        f"\\caption{{Model coverage of the \\texttt{{{_esc(pool)}}} tier: "
        "checkpoints per model family and size bucket (\\texttt{N (Km)} = N "
        "checkpoints across K models).}}\n\\label{tab:coverage}\n"
        f"\\begin{{tabular}}{{{col}}}\n\\toprule\n{header}\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only",
                    choices=["languages", "benchmarks", "coverage", "coverage_summary"],
                    default=None, help="Generate only one table (default: all).")
    ap.add_argument("--pool", default="external",
                    help="Model-set pool for the coverage table (default: external).")
    ap.add_argument("--outdir", default=str(_ROOT / "configs" / "tables"),
                    help="Directory for the .tex files (default: configs/tables/).")
    args = ap.parse_args()

    builders = {
        "languages": lambda: languages_table(),
        "benchmarks": lambda: benchmarks_table(),
        "coverage": lambda: coverage_table(args.pool),
        "coverage_summary": lambda: coverage_summary_table(args.pool),
    }
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    for name, build in builders.items():
        if args.only and name != args.only:
            continue
        tex = build()
        path = outdir / f"{name}.tex"
        path.write_text(tex)
        print(f"\n===== {name} -> {path} =====\n{tex}")


if __name__ == "__main__":
    main()
